version: "3"

services:
  database:
    image: mysql:8
    container_name: test_diarydb
    environment:
      - MYSQL_DATABASE=diarydb
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1234@#
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init:/usr/lib/mysql
    networks:
      - test-network

  application:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    container_name: app-test01
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/diarydb?useSSL=FALSE&serverTimezone=UTC&useLegacyDatetimeCode=FALSE&allowPublicKeyRetrieval=TRUE
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test1234@#
    networks:
      - test-network
    volumes:
      - .:/var/src/app

networks:
  test-network:
